### ISSUE TITLE
Is page.pageSize.format case-sensitive?

### ISSUE THREAD

**Issue by Slav4ik** [demisto/sane-reports#13]
In webpage: is page.pageSize.format case-sensitive?
https://github.com/demisto/sane-reports/blob/4d8a4e8c1a13b1028bbf85c1b797c54a82a76db1/reportsServer.js#L70

**Comment by dorsha** [comment]
I think they are.
Here you can find information regarding `format` and other configuration of `paperSize`.
http://phantomjs.org/api/webpage/property/paper-size.html

**Comment by Slav4ik** [comment]
Actually, looks like insensitive. 
https://github.com/ariya/phantomjs/blob/35c0cbb82b614268a09cf4728d0ad19634a7c6de/src/webpage.cpp#L1249

Your opinion?

**Comment by dorsha** [comment]
👍 
Seems you are right.
