### ISSUE TITLE
Add value to the Bars in Charts

### ISSUE THREAD

**Issue by Slav4ik** [demisto/sane-reports#14]
in BarChart: can you add a boolean to put the value on top of the bar? 
http://jsfiddle.net/43to7n0x/
<Bar ... legend />

**Comment by dorsha** [comment]
Yes, we can add the `label` property. If you already have code for that, you can create PR and we will merge it.

**Comment by dorsha** [comment]
@Slav4ik - FYI, we are going to invest lots of effort to improve and enhance sane-reports in the neat future.

**Comment by Slav4ik** [comment]
Added in commit 68e70d0 Release 1.0.3
