### ISSUE TITLE
Section style fontFamily does not propagate properly 

### ISSUE THREAD

**Issue by karandhodi** [demisto/sane-reports#83]
Is it possible to change the "fontFamily" in "markdown" element? The "fontSize" property works but "fontFamily" doesn't seem to make a change. Thank you.

**Comment by dorsha** [comment]
@Bars92 can you please check this?

**Comment by karandhodi** [comment]
Okay will try the html section. Thank you for the help !

**Comment by Bars92** [comment]
hey @karandhodi, issue was resolved. You may use master branch for the updated version. An npm version will only be released in the following months.

Thank you for your issue and collaboration :)
