### ISSUE TITLE
Using Markdown section

### ISSUE THREAD

**Issue by karandhodi** [demisto/sane-reports#92]
Hi, I have been using the sane-reports package that I installed through NPM. However that package does not have support for Markdown section. What all changes should I do in the files I installed through NPM to enable support for Markdown? Thanks !

**Comment by dorsha** [comment]
Check this example: https://github.com/demisto/sane-reports/blob/master/templates/test.json#L314

**Comment by karandhodi** [comment]
Okay thank you ! Does the NPM installed version has support for HTML type section as well?

**Comment by karandhodi** [comment]
I have cloned the latest Git repo and I am running the command "sudo phantomjs reportsServer.js templates/ctaTemplate_final.json dist/test_ctaNew.pdf".

However the section type HTML is not working in this case

**Comment by karandhodi** [comment]
Okay I was able to figure it out. Thanks !
